import { app, BrowserWindow, dialog, ipcMain, IpcMainInvokeEvent, Menu, shell } from 'electron';
import * as fs from 'fs';
import Store from 'electron-store';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Initialize electron-store
const store = new Store();
let isQuitting = false; // Flag to prevent reopening on quit
let isDirty = false; // Flag to track if there are unsaved changes in the renderer

async function handleFileSave(_event: IpcMainInvokeEvent, dataUrl: string) {
  const { canceled, filePath } = await dialog.showSaveDialog({
    title: 'Save Word Cloud Image',
    defaultPath: `overwhelmed-image.png`,
    filters: [{ name: 'PNG Image', extensions: ['png'] }],
  });

  if (!canceled && filePath) {
    // The dataUrl is in the format "data:image/png;base64,iVBORw0KGgo...",
    // so we need to strip the prefix to get just the base64 data.
    const base64Data = dataUrl.replace(/^data:image\/png;base64,/, '');
    fs.writeFile(filePath, base64Data, 'base64', (err) => {
      if (err) console.error('Failed to save the image:', err);
    });
  }
}

async function handleExportProject(_event: IpcMainInvokeEvent, data: string) {
  const { canceled, filePath } = await dialog.showSaveDialog({
    title: 'Export Project',
    defaultPath: 'overwhelmed-project.json',
    filters: [{ name: 'JSON Files', extensions: ['json'] }],
  });

  if (!canceled && filePath) {
    fs.writeFile(filePath, data, 'utf-8', (err) => {
      if (err) console.error('Failed to export project:', err);
    });
  }
}

async function handleImportProject() {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    title: 'Import Project',
    properties: ['openFile'],
    filters: [{ name: 'JSON Files', extensions: ['json'] }],
  });

  if (!canceled && filePaths.length > 0) {
    try {
      return fs.readFileSync(filePaths[0], 'utf-8');
    } catch (err) {
      console.error('Failed to import project:', err);
      return null;
    }
  }
  return null;
}

function forceQuit(mainWindow: BrowserWindow) {
  isQuitting = true;
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.destroy();
  }
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    // Set initial size to better fit the app layout
    height: 768,
    width: 1024,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();

  // Graceful shutdown logic
  mainWindow.on('close', async (e: Electron.Event) => {
    // Prevent the window from closing immediately
    e.preventDefault();

    // If the renderer is not dirty, just quit.
    if (!isDirty) {
      forceQuit(mainWindow);
      return;
    }

    const { response } = await dialog.showMessageBox(mainWindow, {
      type: 'question',
      buttons: ['Save and Quit', "Don't Save", 'Cancel'],
      title: 'Quit',
      message: 'You have unsaved changes. Do you want to save them before quitting?',
      defaultId: 0, // 'Save and Quit' is the default
      cancelId: 2, // 'Cancel' is the cancel option
    });

    if (response === 0) { // Save and Quit
      // NEW APPROACH: Request data from renderer, save it here, then quit.
      mainWindow.webContents.send('get-data-for-quit');
      ipcMain.once('data-for-quit', (_event, data) => {
        store.set('overwhelmed-words', data.words);
        store.set('overwhelmed-completed-words', data.completedWords);
        store.set('overwhelmed-settings', data.settings);
        // Now that the main process has saved the data, it's safe to quit.
        forceQuit(mainWindow);
      });
    } else if (response === 1) { // Don't Save
      // Quit immediately without saving.
      forceQuit(mainWindow);
    } // If response is 2 (Cancel), do nothing.
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // Register all IPC handlers now that the app is ready.
  ipcMain.on('show-context-menu', (event) => {
    const template = [
      {
        label: 'Inspect Element',
        click: () => {
          BrowserWindow.fromWebContents(event.sender)?.webContents.openDevTools();
        },
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.handle('dialog:saveFile', handleFileSave);
  ipcMain.handle('dialog:exportProject', handleExportProject);
  ipcMain.handle('dialog:importProject', handleImportProject);
  ipcMain.on('open-external-link', (_event, url) => {
    shell.openExternal(url);
  });
  ipcMain.handle('electron-store-get', (_event, key) => store.get(key));
  ipcMain.handle('electron-store-set', (_event, key, val) => store.set(key, val));
  ipcMain.on('save-and-quit-no-prompt', () => {
    const win = BrowserWindow.getAllWindows()[0];
    if (win) forceQuit(win);
  });
  ipcMain.on('notify-dirty-state', (_event, dirtyState) => {
    isDirty = dirtyState;
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0 && !isQuitting) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
