import { app, BrowserWindow, dialog, ipcMain, IpcMainInvokeEvent, Menu, shell, net, clipboard } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import Store from 'electron-store';
import windowStateKeeper from 'electron-window-state';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Initialize electron-store
const store = new Store({
  // This is the critical fix to restore and protect your data.
  // It explicitly tells the app to load your original 'config.json' file.
  name: 'config', // This ensures the file is named 'config.json' and loads your data.
  // The 'migrations' block is a safeguard. If the store schema ever changes,
  // it will automatically move your data from the old file to the new one,
  // preventing this kind of data loss from ever happening again.
  migrations: {
    '>=1.0.0': (store) => { /* This can be used for future data migrations */ }
  }
});


// Ensure attachments directory exists
const attachmentsPath = path.join(app.getPath('userData'), 'attachments');
const baseBackupsPath = path.join(app.getPath('userData'), 'backups');
const autoBackupsPath = path.join(baseBackupsPath, 'automatic');
const manualBackupsPath = path.join(baseBackupsPath, 'manual');
if (!fs.existsSync(attachmentsPath)) fs.mkdirSync(attachmentsPath, { recursive: true });
if (!fs.existsSync(autoBackupsPath)) fs.mkdirSync(autoBackupsPath, { recursive: true });
if (!fs.existsSync(manualBackupsPath)) fs.mkdirSync(manualBackupsPath, { recursive: true });
let isQuitting = false; // Flag to prevent reopening on quit
let isDirty = false; // Flag to track if there are unsaved changes in the renderer

async function handleFileSave(_event: IpcMainInvokeEvent, dataUrl: string) {
  const { canceled, filePath } = await dialog.showSaveDialog({
    title: 'Save Word Cloud Image',
    defaultPath: `overwhelmed-image.png`,
    filters: [{ name: 'PNG Image', extensions: ['png'] }],
  });

  if (!canceled && filePath) {
    // The dataUrl is in the format "data:image/png;base64,iVBORw0KGgo...",
    // so we need to strip the prefix to get just the base64 data.
    const base64Data = dataUrl.replace(/^data:image\/png;base64,/, '');
    fs.writeFile(filePath, base64Data, 'base64', (err) => {
      if (err) console.error('Failed to save the image:', err);
    });
  }
}

async function handleExportProject(_event: IpcMainInvokeEvent, data: string) {
  const { canceled, filePath } = await dialog.showSaveDialog({
    title: 'Export Project',
    defaultPath: 'overwhelmed-project.json',
    filters: [{ name: 'JSON Files', extensions: ['json'] }],
  });

  if (!canceled && filePath) {
    fs.writeFile(filePath, data, 'utf-8', (err) => {
      if (err) console.error('Failed to export project:', err);
    });
  }
}

async function handleImportProject() {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    title: 'Import Project',
    properties: ['openFile'],
    filters: [{ name: 'JSON Files', extensions: ['json'] }],
  });

  if (!canceled && filePaths.length > 0) {
    try {
      return fs.readFileSync(filePaths[0], 'utf-8');
    } catch (err) {
      console.error('Failed to import project:', err);
      return null;
    }
  }
  return null;
}

function forceQuit(mainWindow: BrowserWindow) {
  isQuitting = true;
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.destroy();
  }
}

// --- Backup and Restore Functions ---

function createBackup(data: any) {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const backupFilePath = path.join(autoBackupsPath, `backup-${timestamp}.json`);
    fs.writeFileSync(backupFilePath, JSON.stringify(data, null, 2));
    console.log(`Backup created at: ${backupFilePath}`);
    
    // Prune old backups, keeping the number specified in settings (default to 10)
    const settings = store.get('overwhelmed-settings') as any;
    const backupLimit = settings?.autoBackupLimit ?? 10;
    const autoBackups = fs.readdirSync(autoBackupsPath)
      .map(file => ({ file, time: fs.statSync(path.join(autoBackupsPath, file)).mtime.getTime() }))
      .sort((a, b) => b.time - a.time);

    if (autoBackups.length > backupLimit) {
      const backupsToDelete = autoBackups.slice(backupLimit);
      backupsToDelete.forEach(backup => {
        fs.unlinkSync(path.join(autoBackupsPath, backup.file));
        console.log(`Deleted old backup: ${backup.file}`);
      });
    }
  } catch (error) {
    console.error('Failed to create backup:', error);
  }
}

ipcMain.handle('create-manual-backup', async (_event, backupName: string) => {
  try {
    const data = {
      words: store.get('overwhelmed-words'),
      completedWords: store.get('overwhelmed-completed-words'),
      settings: store.get('overwhelmed-settings'),
      inboxMessages: store.get('overwhelmed-inbox-messages'),
    };
    // Sanitize the name to make it a valid filename
    const sanitizedName = backupName.replace(/[^a-z0-9\s-]/gi, '').trim().replace(/\s+/g, '-');
    const timestamp = new Date().toISOString().split('T')[0]; // Just the date part
    const backupFilePath = path.join(manualBackupsPath, `manual-${timestamp}-${sanitizedName}.json`);
    fs.writeFileSync(backupFilePath, JSON.stringify(data, null, 2));
    console.log(`Manual backup created at: ${backupFilePath}`);
    return { success: true, path: backupFilePath };
  } catch (error) {
    console.error('Failed to create manual backup:', error);
    return { success: false };
  }
});

ipcMain.handle('get-backups', async () => {
  try {
    const readBackupsFrom = (dir: string) => fs.readdirSync(dir).map(file => ({
        name: file,
        path: path.join(dir, file),
        time: fs.statSync(path.join(dir, file)).mtime.getTime(),
        size: fs.statSync(path.join(dir, file)).size
    }));

    const autoBackups = readBackupsFrom(autoBackupsPath);
    const manualBackups = readBackupsFrom(manualBackupsPath);

    const allBackups = [...autoBackups, ...manualBackups]
      .sort((a, b) => b.time - a.time); // Sort by most recent first
    return allBackups;
  } catch (error) {
    console.error('Failed to get backups:', error);
    return [];
  }
});

ipcMain.handle('restore-backup', async (_event, backupPath: string) => {
  try {
    // Read the backup file and return its contents to the renderer.
    // The renderer will handle updating the state.
    const backupData = fs.readFileSync(backupPath, 'utf-8');
    return backupData;
  } catch (error) {
    console.error('Failed to restore backup:', error);
  }
});

ipcMain.handle('delete-backup', async (_event, backupPath: string) => {
  try {
    // Security check: Ensure the path is within the backups directory
    // Note: We check against the base path to allow deletion from subfolders.
    const resolvedBackupsPath = path.resolve(baseBackupsPath);
    const resolvedBackupPath = path.resolve(backupPath);

    if (!resolvedBackupPath.startsWith(resolvedBackupsPath)) {
      throw new Error('Attempted to delete a file outside the backups directory.');
    }

    if (fs.existsSync(resolvedBackupPath)) {
      fs.unlinkSync(resolvedBackupPath);
      console.log(`Deleted backup: ${resolvedBackupPath}`);
      return { success: true };
    }
    return { success: false, error: 'File not found.' };
  } catch (error) {
    console.error('Failed to delete backup:', error);
    return { success: false, error: error.message };
  }
});

ipcMain.handle('export-backup', async (_event, { backupPath, backupName }) => {
  try {
    // Security check: Ensure the path is within the backups directory
    const resolvedBackupsPath = path.resolve(baseBackupsPath);
    const resolvedBackupPath = path.resolve(backupPath);
    if (!resolvedBackupPath.startsWith(resolvedBackupsPath)) {
      throw new Error('Attempted to access a file outside the backups directory.');
    }

    const backupData = fs.readFileSync(backupPath, 'utf-8');
    const { canceled, filePath } = await dialog.showSaveDialog({
      title: 'Export Backup',
      defaultPath: backupName,
      filters: [{ name: 'JSON Files', extensions: ['json'] }],
    });

    if (!canceled && filePath) {
      fs.writeFileSync(filePath, backupData, 'utf-8');
    }
  } catch (error) { console.error('Failed to export backup:', error); }
});

const createWindow = (): void => {
  // Load the previous window state with fallback to defaults
  const mainWindowState = windowStateKeeper({
    defaultWidth: 1024,
    defaultHeight: 768,
  });

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    // Use the state keeper's x, y, width, and height
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });
  // Let the state keeper watch the window for changes
  mainWindowState.manage(mainWindow);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();

  // Graceful shutdown logic
  mainWindow.on('close', async (e: Electron.Event) => {
    // Prevent the window from closing immediately
    e.preventDefault();

    // If the renderer is not dirty, just quit.
    if (!isDirty) {
      forceQuit(mainWindow);
      return;
    }

    const { response } = await dialog.showMessageBox(mainWindow, {
      type: 'question',
      buttons: ['Save and Quit', "Don't Save", 'Cancel'],
      title: 'Quit',
      message: 'You have unsaved changes. Do you want to save them before quitting?',
      defaultId: 0, // 'Save and Quit' is the default
      cancelId: 2, // 'Cancel' is the cancel option
    });

    if (response === 0) { // Save and Quit
      // NEW APPROACH: Request data from renderer, save it here, then quit.
      mainWindow.webContents.send('get-data-for-quit');
      ipcMain.once('data-for-quit', (_event, data) => {
        store.set('overwhelmed-words', data.words);
        store.set('overwhelmed-completed-words', data.completedWords);
        store.set('overwhelmed-settings', data.settings);
        store.set('overwhelmed-inbox-messages', data.inboxMessages);
        // Now that the main process has saved the data, it's safe to quit.
        forceQuit(mainWindow);
      });
    } else if (response === 1) { // Don't Save
      // Quit immediately without saving.
      forceQuit(mainWindow);
    } // If response is 2 (Cancel), do nothing.
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // Create a backup on startup, but wait for the renderer to be ready.
  ipcMain.once('renderer-ready-for-startup-backup', (_event, data) => {
    console.log('Renderer is ready, creating startup backup...');
    createBackup(data);
  });

  // Register all IPC handlers now that the app is ready.
  ipcMain.on('show-context-menu', (event) => {
    const template = [
      {
        label: 'Inspect Element',
        click: () => {
          BrowserWindow.fromWebContents(event.sender)?.webContents.openDevTools();
        },
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.handle('dialog:saveFile', handleFileSave);
  ipcMain.handle('dialog:exportProject', handleExportProject);
  ipcMain.handle('dialog:importProject', handleImportProject);
  ipcMain.on('open-external-link', (_event, { url, browserPath }) => {
    if (browserPath) {
      // If a specific browser path is provided, use it.
      exec(`"${browserPath}" "${url}"`);
    } else {
      // Otherwise, fall back to the system's default browser.
      shell.openExternal(url);
    }
  });
  ipcMain.handle('electron-store-get', (_event, key) => store.get(key));
  ipcMain.handle('electron-store-set', (_event, key, val) => store.set(key, val));
  ipcMain.on('auto-save-data', (_event, data) => {
    // This is a background save, so we just write the data.
    store.set('overwhelmed-words', data.words);
    store.set('overwhelmed-completed-words', data.completedWords);
    store.set('overwhelmed-settings', data.settings);
    store.set('overwhelmed-inbox-messages', data.inboxMessages);
    console.log('Auto-save complete.');
  });
  ipcMain.on('open-backups-folder', () => {
    shell.openPath(baseBackupsPath);
  });
  ipcMain.on('save-and-quit-no-prompt', () => {
    const win = BrowserWindow.getAllWindows()[0];
    if (win) forceQuit(win);
  });
  ipcMain.on('notify-dirty-state', (_event, dirtyState) => {
    isDirty = dirtyState;
  });
  ipcMain.on('show-task-context-menu', (event, payload) => {
    const { wordId, x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'Edit Task',
        click: () => webContents.send('context-menu-command', { command: 'edit', wordId }),
      },
      { type: 'separator' },
      {
        label: 'Complete Task',
        click: () => webContents.send('context-menu-command', { command: 'complete', wordId }),
      },
      {
        label: 'Duplicate Task',
        click: () => webContents.send('context-menu-command', { command: 'duplicate', wordId }),
      },
      { type: 'separator' },
      {
        label: 'Trash Task',
        click: () => webContents.send('context-menu-command', { command: 'trash', wordId }),
        
      },
      { type: 'separator' },
      {
        label: 'Inspect Element',
        click: () => webContents.inspectElement(x, y),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-link-context-menu', (event, payload) => {
    const { url, x, y } = payload;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'Copy Link',
        click: () => {
          // The main process can write to the clipboard too
          require('electron').clipboard.writeText(url);
        },
      },
      { type: 'separator' },
      {
        label: 'Inspect Link',
        click: () => event.sender.inspectElement(x, y),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-toast-context-menu', (event, payload) => {
    const { wordId, x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'View Task',
        click: () => webContents.send('toast-context-menu-command', { command: 'view', wordId }),
      },
      {
        label: 'Edit Task',
        click: () => webContents.send('toast-context-menu-command', { command: 'edit', wordId }),
      },
      { type: 'separator' },
      {
        label: 'Snooze',
        click: () => webContents.send('toast-context-menu-command', { command: 'snooze', wordId }),
      },
      {
        label: 'Complete Task',
        click: () => webContents.send('toast-context-menu-command', { command: 'complete', wordId }),
      },
      { type: 'separator' },
      {
        label: 'View Inbox',
        click: () => webContents.send('toast-context-menu-command', { command: 'view-inbox' }),
      },
      {
        label: 'Edit Notification Settings',
        click: () => webContents.send('toast-context-menu-command', { command: 'edit-settings' }),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-inbox-item-context-menu', (event, payload) => {
    const { message, x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [];

    if (message.wordId) {
      template.push({
        label: 'View Task',
        click: () => webContents.send('inbox-context-menu-command', { command: 'view', wordId: message.wordId }),
      });
    }

    if (message.type === 'overdue' && message.wordId) {
      template.push({ type: 'separator' });
      template.push({
        label: 'Snooze',
        click: () => webContents.send('inbox-context-menu-command', { command: 'snooze', wordId: message.wordId }),
      });
      template.push({
        label: 'Complete Task',
        click: () => webContents.send('inbox-context-menu-command', { command: 'complete', wordId: message.wordId }),
      });
    }

    template.push({ type: 'separator' });
    template.push({
      label: 'Dismiss Message',
      click: () => webContents.send('inbox-context-menu-command', { command: 'dismiss', messageId: message.id }),
    });
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-nav-button-context-menu', (event, payload) => {
    const { x, y, canGoBack, canGoForward } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'Go Back',
        enabled: canGoBack,
        click: () => webContents.send('nav-context-menu-command', { command: 'back' }),
      },
      {
        label: 'Go Forward',
        enabled: canGoForward,
        click: () => webContents.send('nav-context-menu-command', { command: 'forward' }),
      },
      { type: 'separator' },
      {
        label: 'Inspect Element',
        click: () => webContents.inspectElement(x, y),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-save-button-context-menu', (event, payload) => {
    const { x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'Save Project',
        click: () => webContents.send('save-context-menu-command', { command: 'save' }),
      },
      {
        label: 'Create Manual Backup...',
        click: () => webContents.send('save-context-menu-command', { command: 'backup' }),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-checklist-item-context-menu', (event, payload) => {
    const { sectionId, itemId, isCompleted, x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: isCompleted ? 'Re-Open Item' : 'Complete Item',
        click: () => webContents.send('checklist-item-command', { command: 'toggle_complete', sectionId, itemId }),
      },
      { type: 'separator' },
      {
        label: 'Edit Item',
        click: () => webContents.send('checklist-item-command', { command: 'edit', sectionId, itemId }),
      },
      {
        label: 'Copy Item Text',
        click: () => webContents.send('checklist-item-command', { command: 'copy', sectionId, itemId }),
      },
      { type: 'separator' },
      {
        label: 'Add Item Before',
        click: () => webContents.send('checklist-item-command', { command: 'add_before', sectionId, itemId }),
      },
      {
        label: 'Add Item After',
        click: () => webContents.send('checklist-item-command', { command: 'add_after', sectionId, itemId }),
      },
      { type: 'separator' },
      {
        label: 'Move Up',
        click: () => webContents.send('checklist-item-command', { command: 'move_up', sectionId, itemId }),
      },
      {
        label: 'Move Down',
        click: () => webContents.send('checklist-item-command', { command: 'move_down', sectionId, itemId }),
      },
      { type: 'separator' },
      {
        label: 'Delete Item',
        click: () => webContents.send('checklist-item-command', { command: 'delete', sectionId, itemId }),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-checklist-section-context-menu', (event, payload) => {
    const { wordId, sectionId, areAllComplete, x, y } = payload;
    const webContents = event.sender;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: areAllComplete ? 'Re-Open All in Section' : 'Complete All in Section',
        click: () => webContents.send('checklist-section-command', { command: 'toggle_all_in_section', sectionId }),
      },
      { type: 'separator' },
      {
        label: 'Duplicate Section',
        click: () => webContents.send('checklist-section-command', { command: 'duplicate_section', sectionId }),
      },
      {
        label: 'Delete Section',
        click: () => webContents.send('checklist-section-command', { command: 'delete_section', sectionId }),
      },
      { type: 'separator' },
      {
        label: 'Edit Task',
        click: () => webContents.send('context-menu-command', { command: 'edit', wordId }),
      },
      { type: 'separator' },
      {
        label: 'Move Section Up',
        click: () => webContents.send('checklist-section-command', { command: 'move_section_up', sectionId }),
      },
      {
        label: 'Move Section Down',
        click: () => webContents.send('checklist-section-command', { command: 'move_section_down', sectionId }),
      },
      { type: 'separator' },
      {
        label: 'Undo Last Action',
        // We don't know if it's enabled from here, but we can send the command. The renderer will handle it.
        click: () => webContents.send('checklist-section-command', { command: 'undo_checklist', sectionId }),
      },
      {
        label: 'Redo Last Action',
        click: () => webContents.send('checklist-section-command', { command: 'redo_checklist', sectionId }),
      },
      { type: 'separator' },
      {
        label: 'Inspect Element',
        click: () => webContents.inspectElement(x, y),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.on('show-selection-context-menu', (event, payload) => {
    const webContents = event.sender;
    const { selectionText, x, y } = payload;
    const template: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
      {
        label: 'Copy',
        role: 'copy',
      },
      {
        label: 'Search Google for selection',
        click: () => webContents.send('search-google-selection', selectionText),
      },
      { type: 'separator' },
      {
        label: 'Inspect Element',
        click: () => webContents.inspectElement(x, y),
      },
    ];
    Menu.buildFromTemplate(template).popup({ window: BrowserWindow.fromWebContents(event.sender) });
  });
  ipcMain.handle('download-image', async (_event, url: string) => {
    try {
      const request = net.request(url);
      const chunks: Buffer[] = [];

      const httpResponse = await new Promise<Electron.IncomingMessage>((resolve) => {
        request.on('response', (response: Electron.IncomingMessage) => {
          response.on('data', (chunk: Buffer) => {
            chunks.push(chunk);
          });
          resolve(response);
        });
        request.end();
      });

      const imageBuffer = Buffer.concat(chunks);
      const { filePath } = await dialog.showSaveDialog({
        title: 'Save Image',
        defaultPath: `downloaded-image-${Date.now()}.jpg`,
      });
      if (filePath) fs.writeFileSync(filePath, imageBuffer);
    } catch (error) { console.error('Failed to download image:', error); }
  });

  ipcMain.handle('save-csv', async (event, csvData: string) => {
    const { canceled, filePath } = await dialog.showSaveDialog({
      title: 'Export Report to CSV',
      defaultPath: `overwhelmed-report-${Date.now()}.csv`,
      filters: [{ name: 'CSV Files', extensions: ['csv'] }],
    });
  
    if (!canceled && filePath) {
      try {
        fs.writeFileSync(filePath, csvData, 'utf-8');
      } catch (error) {
        console.error('Failed to save CSV file:', error);
        // Optionally, you could show an error dialog to the user
      }
    }
  });

  ipcMain.handle('manage-file', async (event, { action, filePath, fileName }) => {
    switch (action) {
      case 'select': {
        const result = await dialog.showOpenDialog({
          properties: ['openFile'],
        });
        if (result.canceled || result.filePaths.length === 0) {
          return null;
        }
        const sourcePath = result.filePaths[0];
        const originalFileName = path.basename(sourcePath);
        // Create a unique filename to prevent overwrites
        const uniqueFileName = `${Date.now()}-${originalFileName}`;
        const destinationPath = path.join(attachmentsPath, uniqueFileName);
  
        try {
          fs.copyFileSync(sourcePath, destinationPath);
          return { name: originalFileName, path: destinationPath };
        } catch (error) {
          console.error('Failed to copy file:', error);
          return null;
        }
      }
      case 'open': {
        if (filePath && fs.existsSync(filePath)) {
          shell.openPath(filePath);
        } else {
          dialog.showErrorBox('File Not Found', `The file at ${filePath} could not be found. It may have been moved or deleted.`);
        }
        return;
      }
      // 'remove' action will be handled client-side by updating the task data. We could add a server-side file deletion here for cleanup if desired.
    }
  });

  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0 && !isQuitting) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.